apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-optimizer-controller
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: memory-optimizer
        image: memory-optimizer:v1.0.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
